from enum import Enum


class Zones(Enum):
    LIMSA_LOMINSA = "Limsa Lominsa"
    MIDDLE_LA_NOSCEA = "Middle La Noscea"
    LOWER_LA_NOSCEA = "Lower La Noscea"
    EASTERN_LA_NOSCEA = "Eastern La Noscea"
    WESTERN_LA_NOSCEA = "Western La Noscea"
    UPPER_LA_NOSCEA = "Upper La Noscea"
    OUTER_LA_NOSCEA = "Outer La Noscea"
    THE_MIST = "The Mist"
    GRIDANIA = "Gridania"
    CENTRAL_SHROUD = "Central Shroud"
    EAST_SHROUD = "East Shroud"
    SOUTH_SHROUD = "South Shroud"
    NORTH_SHROUD = "North Shroud"
    THE_LAVENDER_BEDS = "The Lavender Beds"
    ULDAH = "Ul'dah"
    WESTERN_THANALAN = "Western Thanalan"
    CENTRAL_THANALAN = "Central Thanalan"
    EASTERN_THANALAN = "Eastern Thanalan"
    SOUTHERN_THANALAN = "Southern Thanalan"
    NORTHERN_THANALAN = "Northern Thanalan"
    THE_GOBLET = "The Goblet"
    ISHGARD = "Ishgard"
    COERTHAS_CENTRAL_HIGHLANDS = "Coerthas Central Highlands"
    COERTHAS_WESTERN_HIGHLANDS = "Coerthas Western Highlands"
    THE_SEA_OF_CLOUDS = "The Sea of Clouds"
    AZYS_LLA = "Azys Lla"
    THE_DIADEM = "The Diadem"
    IDYLLSHIRE = "Idyllshire"
    THE_DRAVANIAN_FORELANDS = "The Dravanian Forelands"
    THE_DRAVANIAN_HINTERLANDS = "The Dravanian Hinterlands"
    THE_CHURNING_MISTS = "The Churning Mists"
    MOR_DHONA = "Mor Dhona"
    RHALGRS_REACH = "Rhalgr's Reach"
    THE_FRINGES = "The Fringes"
    THE_PEAKS = "The Peaks"
    THE_LOCHS = "The Lochs"
    KUGANE = "Kugane"
    SHIROGANE = "Shirogane"
    THE_RUBY_SEA = "The Ruby Sea"
    YANXIA = "Yanxia"
    THE_AZIM_STEPPE = "The Azim Steppe"
    EUREKA_ANEMOS = "Eureka Anemos"
    EUREKA_PAGOS = "Eureka Pagos"
    EUREKA_PYROS = "Eureka Pyros"
